motors = [
  { num = 1, name = "left_hip_yaw_joint",    type = "EC-A2806-P2-36", api_type = 8, chan = 2, canid =  1, kp_in_use = 10,   kd_in_use = 0.8,                                    pos_min = 0.0,   pos_max = 0.0  },
]
