motors = [
  {num = 31, name = "FT_SERVO_1", type = "SCS0037-C001", api_type = 4, port = "/dev/ttyACM0", baud = 500000, canid = 1, kp_in_use = 0.0, kd_in_use = 0.0, pos_min = 0.0, pos_max = 4.712389},
]
